### ISSUE TITLE
FR:简洁命令行换行

### ISSUE THREAD

**Issue by A2Sumie** [biliup/biliup-rs#170]
之前相关issues都说使用yaml换行语法，没有有关命令行中简介换行的说明
我的场景是，某软件完成采集转码后可以指定运行一个批处理文件
虽然不是不能用批处理做一个yaml生成器但是很蛋疼，如果可以在命令行直接用某种换行符就好了

**Comment by kimycai** [comment]
我也想要有个换行符，无奈试遍了也换不了行，请大佬能考虑以下换行符

**Comment by kimycai** [comment]
> 命令行可以用引号包裹简介实现换行

你是说用引号把简介内容圈起来，简介格式是什么就会显示什么，是换行的就会显示另起一行了，是这样吗，用双引号吗？

**Comment by dreammu** [comment]
> > 命令行可以用引号包裹简介实现换行
> 
> 你是说用引号把简介内容圈起来，简介格式是什么就会显示什么，是换行的就会显示另起一行了，是这样吗，用双引号吗？

单双应该都可以，但是里边如果还有引号可能需要转义

**Comment by kimycai** [comment]
> > > 命令行可以用引号包裹简介实现换行
> > 
> > 
> > 你是说用引号把简介内容圈起来，简介格式是什么就会显示什么，是换行的就会显示另起一行了，是这样吗，用双引号吗？
> 
> 单双应该都可以，但是里边如果还有引号可能需要转义

哦测试过了，引号内有回车换行，上传命令就会出错，不知道你的代码是什么写的

**Comment by dreammu** [comment]
> 
> > 单双应该都可以，但是里边如果还有引号可能需要转义
> 
> 转义用的是哪个字符，如何转义文件名中的感叹号!和单引号'，上传时总是会出错，需要变成中文字符才行，很苦恼，不知道你有没有办法？
文件名直接用tab补全挺方便的，转义细节不知道你的用法，可以自己找找教程。

**Comment by kimycai** [comment]
> > > 命令行可以用引号包裹简介实现换行
> > 
> > 
> > 你是说用引号把简介内容圈起来，简介格式是什么就会显示什么，是换行的就会显示另起一行了，是这样吗，用双引号吗？
> 
> 单双应该都可以，但是里边如果还有引号可能需要转义

你的系统环境是linux吧，我用的windows

**Comment by dreammu** [comment]
> > > > 命令行可以用引号包裹简介实现换行
> > > 
> > > 
> > > 你是说用引号把简介内容圈起来，简介格式是什么就会显示什么，是换行的就会显示另起一行了，是这样吗，用双引号吗？
> > 
> > 
> > 单双应该都可以，但是里边如果还有引号可能需要转义
> 
> 哦测试过了，引号内有回车换行，上传命令就会出错，不知道你的代码是什么写的

方便提供下报错吗

**Comment by kimycai** [comment]
> > > > > 命令行可以用引号包裹简介实现换行
> > > > 
> > > > 
> > > > 你是说用引号把简介内容圈起来，简介格式是什么就会显示什么，是换行的就会显示另起一行了，是这样吗，用双引号吗？
> > > 
> > > 
> > > 单双应该都可以，但是里边如果还有引号可能需要转义
> > 
> > 
> > 哦测试过了，引号内有回车换行，上传命令就会出错，不知道你的代码是什么写的
> 
> 方便提供下报错吗

thread 'main' panicked at crates\biliup-cli\src\uploader.rs:78:34:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by kimycai** [comment]
> > > > > 命令行可以用引号包裹简介实现换行
> > > > 
> > > > 
> > > > 你是说用引号把简介内容圈起来，简介格式是什么就会显示什么，是换行的就会显示另起一行了，是这样吗，用双引号吗？
> > > 
> > > 
> > > 单双应该都可以，但是里边如果还有引号可能需要转义
> > 
> > 
> > 哦测试过了，引号内有回车换行，上传命令就会出错，不知道你的代码是什么写的
> 
> 方便提供下报错吗

刚才没注意，我的简介里有双引号，可能是这个原因造成的，我再试试

**Comment by kimycai** [comment]
> > > > > 命令行可以用引号包裹简介实现换行
> > > > 
> > > > 
> > > > 你是说用引号把简介内容圈起来，简介格式是什么就会显示什么，是换行的就会显示另起一行了，是这样吗，用双引号吗？
> > > 
> > > 
> > > 单双应该都可以，但是里边如果还有引号可能需要转义
> > 
> > 
> > 哦测试过了，引号内有回车换行，上传命令就会出错，不知道你的代码是什么写的
> 
> 方便提供下报错吗

我的简介里有中文字符的双引号，应该不会影响整个命令吧

**Comment by dreammu** [comment]
> > 
> > 
> > 方便提供下报错吗
> 
> thread 'main' panicked at crates\biliup-cli\src\uploader.rs:78:34: index out of bounds: the len is 0 but the index is 0 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

要不加一下项目的QQ群吧，方便一些
